development:
  adapter: mysql
  database: breakfast_manager_dev
  username: root
  password: bsoft

test:
  adapter: mysql
  database: breakfast_manager_test
  username: root
  password: bsoft

production:
  adapter: mysql
  database: breakfast_manager
  username: root
  password: bsoft
